CUDA_VISIBLE_DEVICES=1 python3 test.py ckpt_path=trained/ssd_inception_v2_coco_2017_11_17/inference/frozen_inference_graph.pb labels_path=data/wildlife_label_map.pbtxt file_name=videos/grizzly_bear_2.mp4 save_file_name=results/ssd_inception_v2_coco_2017_11_17/grizzly_bear_2_det_batch_25.mp4 n_frames=0 batch_size=25

CUDA_VISIBLE_DEVICES=1 python3 test.py ckpt_path=trained/ssd_inception_v2_coco_2017_11_17/inference/frozen_inference_graph.pb labels_path=data/wildlife_label_map.pbtxt file_name=videos/grizzly_bear_3.mp4 save_file_name=results/ssd_inception_v2_coco_2017_11_17/grizzly_bear_3_det_batch_25.mp4 n_frames=0 batch_size=25

CUDA_VISIBLE_DEVICES=1 python3 test.py ckpt_path=trained/ssd_inception_v2_coco_2017_11_17/inference/frozen_inference_graph.pb labels_path=data/wildlife_label_map.pbtxt file_name=videos/grizzly_bear_4.mp4 save_file_name=results/ssd_inception_v2_coco_2017_11_17/grizzly_bear_4_det_batch_25.mp4 n_frames=0 batch_size=25

CUDA_VISIBLE_DEVICES=1 python3 test.py ckpt_path=trained/ssd_inception_v2_coco_2017_11_17/inference/frozen_inference_graph.pb labels_path=data/wildlife_label_map.pbtxt file_name=videos/grizzly_bear_5.mp4 save_file_name=results/ssd_inception_v2_coco_2017_11_17/grizzly_bear_5_det_batch_25.mp4 n_frames=0 batch_size=25

CUDA_VISIBLE_DEVICES=1 python3 test.py ckpt_path=trained/ssd_inception_v2_coco_2017_11_17/inference/frozen_inference_graph.pb labels_path=data/wildlife_label_map.pbtxt file_name=videos/grizzly_bear_6.mp4 save_file_name=results/ssd_inception_v2_coco_2017_11_17/grizzly_bear_6_det_batch_25.mp4 n_frames=0 batch_size=25