set -x

CUDA_VISIBLE_DEVICES=1 python3 test.py ckpt_path=trained/first_training_f-rcnn_inception_v2/inference/frozen_inference_graph.pb labels_path=data/wildlife_label_map.pbtxt file_name=videos/deer_zoo_180529_5.MPG save_file_name=results/first_training_f-rcnn_inception_v2/deer_zoo_180529/deer_zoo_180529_5.mkv n_frames=0 batch_size=25

CUDA_VISIBLE_DEVICES=1 python3 test.py ckpt_path=trained/first_training_f-rcnn_inception_v2/inference/frozen_inference_graph.pb labels_path=data/wildlife_label_map.pbtxt file_name=videos/deer_zoo_180529_6.MPG save_file_name=results/first_training_f-rcnn_inception_v2/deer_zoo_180529/deer_zoo_180529_6.mkv n_frames=0 batch_size=25

CUDA_VISIBLE_DEVICES=1 python3 test.py ckpt_path=trained/first_training_f-rcnn_inception_v2/inference/frozen_inference_graph.pb labels_path=data/wildlife_label_map.pbtxt file_name=videos/deer_zoo_180529_7.MPG save_file_name=results/first_training_f-rcnn_inception_v2/deer_zoo_180529/deer_zoo_180529_7.mkv n_frames=0 batch_size=25

CUDA_VISIBLE_DEVICES=1 python3 test.py ckpt_path=trained/first_training_f-rcnn_inception_v2/inference/frozen_inference_graph.pb labels_path=data/wildlife_label_map.pbtxt file_name=videos/deer_zoo_180529_8.MPG save_file_name=results/first_training_f-rcnn_inception_v2/deer_zoo_180529/deer_zoo_180529_8.mkv n_frames=0 batch_size=25

CUDA_VISIBLE_DEVICES=1 python3 test.py ckpt_path=trained/first_training_f-rcnn_inception_v2/inference/frozen_inference_graph.pb labels_path=data/wildlife_label_map.pbtxt file_name=videos/deer_zoo_180529_9.MPG save_file_name=results/first_training_f-rcnn_inception_v2/deer_zoo_180529/deer_zoo_180529_9.mkv n_frames=0 batch_size=25

CUDA_VISIBLE_DEVICES=1 python3 test.py ckpt_path=trained/first_training_f-rcnn_inception_v2/inference/frozen_inference_graph.pb labels_path=data/wildlife_label_map.pbtxt file_name=videos/deer_zoo_180529_10.MPG save_file_name=results/first_training_f-rcnn_inception_v2/deer_zoo_180529/deer_zoo_180529_10.mkv n_frames=0 batch_size=25
