python3 augment.py src_root_dir=/data/acamp/acamp20k/prototype_1_source src_paths=p1_deer.txt bkg_path=/data/acamp/acamp20k/backgrounds/highway border_ratio=0.05 make_square=1 mask_type=1 bkg_iou_thresh=0.0 aug_seq_prefix=p1_deer_h_no_mask only_one_src_obj=1 aug_seq_size=1000 n_aug=0 inclue_src_in_augmented=0 load_bkg=0 bkg_bboxes_csv=/data/acamp/acamp20k_repo/prototype_1/p1_deer_h_1/annotations.csv flip_lr_prob=-1

python3 augment.py src_root_dir=/data/acamp/acamp20k/prototype_1_source src_paths=p1_deer.txt bkg_path=/data/acamp/acamp20k/backgrounds/airport border_ratio=0.05 make_square=1 mask_type=1 bkg_iou_thresh=0.0 aug_seq_prefix=p1_deer_a_no_mask only_one_src_obj=1 aug_seq_size=1000 n_aug=0 inclue_src_in_augmented=0 load_bkg=0 bkg_bboxes_csv=/data/acamp/acamp20k_repo/prototype_1/p1_deer_a_1/annotations.csv flip_lr_prob=-1

python3 augment.py src_root_dir=/data/acamp/acamp20k/prototype_1_source src_paths=p1_coyote.txt bkg_path=/data/acamp/acamp20k/backgrounds/highway border_ratio=0.05 make_square=1 mask_type=1 bkg_iou_thresh=0.0 aug_seq_prefix=p1_coyote_h_no_mask only_one_src_obj=1 aug_seq_size=1000 n_aug=0 inclue_src_in_augmented=0 load_bkg=0 bkg_bboxes_csv=/data/acamp/acamp20k_repo/prototype_1/p1_coyote_h_1/annotations.csv flip_lr_prob=-1

python3 augment.py src_root_dir=/data/acamp/acamp20k/prototype_1_source src_paths=p1_coyote.txt bkg_path=/data/acamp/acamp20k/backgrounds/airport border_ratio=0.05 make_square=1 mask_type=1 bkg_iou_thresh=0.0 aug_seq_prefix=p1_coyote_a_no_mask only_one_src_obj=1 aug_seq_size=1000 n_aug=0 inclue_src_in_augmented=0 load_bkg=0 bkg_bboxes_csv=/data/acamp/acamp20k_repo/prototype_1/p1_coyote_a_1/annotations.csv flip_lr_prob=-1

python3 augment.py src_root_dir=/data/acamp/acamp20k/prototype_1_source src_paths=p1_bear.txt bkg_path=/data/acamp/acamp20k/backgrounds/highway border_ratio=0.05 make_square=1 mask_type=1 bkg_iou_thresh=0.0 aug_seq_prefix=p1_bear_h_no_mask only_one_src_obj=1 aug_seq_size=1000 n_aug=0 inclue_src_in_augmented=0 load_bkg=0 bkg_bboxes_csv=/data/acamp/acamp20k_repo/prototype_1/p1_bear_h_1/annotations.csv flip_lr_prob=-1 visualize=0

python3 augment.py src_root_dir=/data/acamp/acamp20k/prototype_1_source src_paths=p1_bear.txt bkg_path=/data/acamp/acamp20k/backgrounds/airport border_ratio=0.05 make_square=1 mask_type=1 bkg_iou_thresh=0.0 aug_seq_prefix=p1_bear_a_no_mask only_one_src_obj=1 aug_seq_size=1000 n_aug=0 inclue_src_in_augmented=0 load_bkg=0 bkg_bboxes_csv=/data/acamp/acamp20k_repo/prototype_1/p1_bear_a_1/annotations.csv flip_lr_prob=-1

python3 augment.py src_root_dir=/data/acamp/acamp20k/prototype_1_source src_paths=p1_moose.txt bkg_path=/data/acamp/acamp20k/backgrounds/highway border_ratio=0.05 make_square=1 mask_type=1 bkg_iou_thresh=0.0 aug_seq_prefix=p1_moose_h_no_mask only_one_src_obj=1 aug_seq_size=1000 n_aug=0 inclue_src_in_augmented=0 load_bkg=0 bkg_bboxes_csv=/data/acamp/acamp20k_repo/prototype_1/p1_moose_h_1/annotations.csv flip_lr_prob=-1

python3 augment.py src_root_dir=/data/acamp/acamp20k/prototype_1_source src_paths=p1_moose.txt bkg_path=/data/acamp/acamp20k/backgrounds/airport border_ratio=0.05 make_square=1 mask_type=1 bkg_iou_thresh=0.0 aug_seq_prefix=p1_moose_a_no_mask only_one_src_obj=1 aug_seq_size=1000 n_aug=0 inclue_src_in_augmented=0 load_bkg=0 bkg_bboxes_csv=/data/acamp/acamp20k_repo/prototype_1/p1_moose_a_1/annotations.csv flip_lr_prob=-1

