mv labels/bear_1_1 train/labels/
mv labels/bear_1_2 train/labels/
mv labels/bear_1_5 train/labels/
mv labels/bear_1_6 train/labels/
mv labels/bear_2 train/labels/
mv labels/bear_3 train/labels/
mv labels/bear_4 train/labels/
mv labels/bear_5 train/labels/
mv labels/bear_6 train/labels/
mv labels/bear_10_1 train/labels/
mv labels/bear_11_1 train/labels/
mv labels/bear_11_2 train/labels/
mv labels/bear_12_2 train/labels/
mv labels/bear_13_1 train/labels/
mv labels/bear_14_1 train/labels/
mv labels/bear_14_2 train/labels/
mv labels/bear_16_1 train/labels/
mv labels/bear_16_2 train/labels/
mv labels/bear_16_3 train/labels/
mv labels/bear_17_1 train/labels/
mv labels/bear_8_1 train/labels/
mv labels/coyote_1_1 train/labels/
mv labels/coyote_1_2 train/labels/
mv labels/coyote_1_3 train/labels/
mv labels/coyote_2_3 train/labels/
mv labels/coyote_2_4 train/labels/
mv labels/coyote_2_6 train/labels/
mv labels/coyote_2_7 train/labels/
mv labels/coyote_3_1 train/labels/
mv labels/coyote_3_2 train/labels/
mv labels/coyote_3_5 train/labels/
mv labels/coyote_4_1 train/labels/
mv labels/coyote_4_2 train/labels/
mv labels/coyote_5_1 train/labels/
mv labels/coyote_6_1 train/labels/
mv labels/coyote_6_2 train/labels/
mv labels/coyote_8_1 train/labels/
mv labels/coyote_9_1 train/labels/
mv labels/coyote_9_2 train/labels/
mv labels/coyote_9_3 train/labels/
mv labels/deer_1_1 train/labels/
mv labels/deer_1_2 train/labels/
mv labels/deer_2_4 train/labels/
mv labels/deer_3_3 train/labels/
mv labels/deer_3_1 train/labels/
mv labels/deer_3_2 train/labels/
mv labels/deer_4_1 train/labels/
mv labels/deer_6_2 train/labels/
mv labels/deer_6_3 train/labels/
mv labels/deer_6_4 train/labels/
mv labels/deer_12_1 train/labels/
mv labels/deer_9_1 train/labels/
mv labels/deer_8_1 train/labels/
mv labels/moose_1_1 train/labels/
mv labels/moose_1_2 train/labels/
mv labels/moose_2_1 train/labels/
mv labels/moose_2_2 train/labels/
mv labels/moose_4_1 train/labels/
mv labels/moose_4_2 train/labels/
mv labels/moose_4_3 train/labels/
mv labels/moose_5_1 train/labels/
mv labels/moose_5_3 train/labels/
mv labels/moose_5_5 train/labels/
mv labels/moose_5_6 train/labels/
mv labels/moose_5_9 train/labels/
mv labels/moose_5_10 train/labels/
mv labels/moose_6_1 train/labels/
mv labels/moose_6_2 train/labels/
mv labels/moose_6_3 train/labels/
mv labels/moose_7_1 train/labels/
mv labels/moose_8_1 train/labels/
mv labels/moose_9_1 train/labels/
mv labels/moose_10_1 train/labels/
mv labels/moose_10_2 train/labels/
mv labels/moose_11_1 train/labels/
mv labels/moose_12_1 train/labels/
mv labels/moose_12_2 train/labels/
mv labels/moose_12_3 train/labels/
mv labels/moose_13_1 train/labels/
mv labels/moose_15_1 train/labels/
mv labels/moose_15_2 train/labels/
mv labels/moose_15_3 train/labels/
