mv images/bear_1_1 train/images/
mv images/bear_1_2 train/images/
mv images/bear_1_5 train/images/
mv images/bear_1_6 train/images/
mv images/bear_2 train/images/
mv images/bear_3 train/images/
mv images/bear_4 train/images/
mv images/bear_5 train/images/
mv images/bear_6 train/images/
mv images/bear_10_1 train/images/
mv images/bear_11_1 train/images/
mv images/bear_11_2 train/images/
mv images/bear_12_2 train/images/
mv images/bear_13_1 train/images/
mv images/bear_14_1 train/images/
mv images/bear_14_2 train/images/
mv images/bear_16_1 train/images/
mv images/bear_16_2 train/images/
mv images/bear_16_3 train/images/
mv images/bear_17_1 train/images/
mv images/bear_8_1 train/images/
mv images/coyote_1_1 train/images/
mv images/coyote_1_2 train/images/
mv images/coyote_1_3 train/images/
mv images/coyote_2_3 train/images/
mv images/coyote_2_4 train/images/
mv images/coyote_2_6 train/images/
mv images/coyote_2_7 train/images/
mv images/coyote_3_1 train/images/
mv images/coyote_3_2 train/images/
mv images/coyote_3_5 train/images/
mv images/coyote_4_1 train/images/
mv images/coyote_4_2 train/images/
mv images/coyote_5_1 train/images/
mv images/coyote_6_1 train/images/
mv images/coyote_6_2 train/images/
mv images/coyote_8_1 train/images/
mv images/coyote_9_1 train/images/
mv images/coyote_9_2 train/images/
mv images/coyote_9_3 train/images/
mv images/deer_1_1 train/images/
mv images/deer_1_2 train/images/
mv images/deer_2_4 train/images/
mv images/deer_3_3 train/images/
mv images/deer_3_1 train/images/
mv images/deer_3_2 train/images/
mv images/deer_4_1 train/images/
mv images/deer_6_2 train/images/
mv images/deer_6_3 train/images/
mv images/deer_6_4 train/images/
mv images/deer_12_1 train/images/
mv images/deer_9_1 train/images/
mv images/deer_8_1 train/images/
mv images/moose_1_1 train/images/
mv images/moose_1_2 train/images/
mv images/moose_2_1 train/images/
mv images/moose_2_2 train/images/
mv images/moose_4_1 train/images/
mv images/moose_4_2 train/images/
mv images/moose_4_3 train/images/
mv images/moose_5_1 train/images/
mv images/moose_5_3 train/images/
mv images/moose_5_5 train/images/
mv images/moose_5_6 train/images/
mv images/moose_5_9 train/images/
mv images/moose_5_10 train/images/
mv images/moose_6_1 train/images/
mv images/moose_6_2 train/images/
mv images/moose_6_3 train/images/
mv images/moose_7_1 train/images/
mv images/moose_8_1 train/images/
mv images/moose_9_1 train/images/
mv images/moose_10_1 train/images/
mv images/moose_10_2 train/images/
mv images/moose_11_1 train/images/
mv images/moose_12_1 train/images/
mv images/moose_12_2 train/images/
mv images/moose_12_3 train/images/
mv images/moose_13_1 train/images/
mv images/moose_15_1 train/images/
mv images/moose_15_2 train/images/
mv images/moose_15_3 train/images/
