vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set01\V000.vbb' ), 'N:\\Datasets\\Caltech\\set01\V000.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set01\V001.vbb' ), 'N:\\Datasets\\Caltech\\set01\V001.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set01\V002.vbb' ), 'N:\\Datasets\\Caltech\\set01\V002.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set01\V003.vbb' ), 'N:\\Datasets\\Caltech\\set01\V003.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set01\V004.vbb' ), 'N:\\Datasets\\Caltech\\set01\V004.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set01\V005.vbb' ), 'N:\\Datasets\\Caltech\\set01\V005.txt', 0 )

vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set02\V000.vbb' ), 'N:\\Datasets\\Caltech\\set02\V000.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set02\V001.vbb' ), 'N:\\Datasets\\Caltech\\set02\V001.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set02\V002.vbb' ), 'N:\\Datasets\\Caltech\\set02\V002.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set02\V003.vbb' ), 'N:\\Datasets\\Caltech\\set02\V003.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set02\V004.vbb' ), 'N:\\Datasets\\Caltech\\set02\V004.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set02\V005.vbb' ), 'N:\\Datasets\\Caltech\\set02\V005.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set02\V006.vbb' ), 'N:\\Datasets\\Caltech\\set02\V006.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set02\V007.vbb' ), 'N:\\Datasets\\Caltech\\set02\V007.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set02\V008.vbb' ), 'N:\\Datasets\\Caltech\\set02\V008.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set02\V009.vbb' ), 'N:\\Datasets\\Caltech\\set02\V009.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set02\V010.vbb' ), 'N:\\Datasets\\Caltech\\set02\V010.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set02\V011.vbb' ), 'N:\\Datasets\\Caltech\\set02\V011.txt', 0 )

vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set03\V000.vbb' ), 'N:\\Datasets\\Caltech\\set03\V000.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set03\V001.vbb' ), 'N:\\Datasets\\Caltech\\set03\V001.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set03\V002.vbb' ), 'N:\\Datasets\\Caltech\\set03\V002.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set03\V003.vbb' ), 'N:\\Datasets\\Caltech\\set03\V003.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set03\V004.vbb' ), 'N:\\Datasets\\Caltech\\set03\V004.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set03\V005.vbb' ), 'N:\\Datasets\\Caltech\\set03\V005.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set03\V006.vbb' ), 'N:\\Datasets\\Caltech\\set03\V006.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set03\V007.vbb' ), 'N:\\Datasets\\Caltech\\set03\V007.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set03\V008.vbb' ), 'N:\\Datasets\\Caltech\\set03\V008.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set03\V009.vbb' ), 'N:\\Datasets\\Caltech\\set03\V009.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set03\V010.vbb' ), 'N:\\Datasets\\Caltech\\set03\V010.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set03\V011.vbb' ), 'N:\\Datasets\\Caltech\\set03\V011.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set03\V012.vbb' ), 'N:\\Datasets\\Caltech\\set03\V012.txt', 0 )

vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set04\V000.vbb' ), 'N:\\Datasets\\Caltech\\set04\V000.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set04\V001.vbb' ), 'N:\\Datasets\\Caltech\\set04\V001.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set04\V002.vbb' ), 'N:\\Datasets\\Caltech\\set04\V002.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set04\V003.vbb' ), 'N:\\Datasets\\Caltech\\set04\V003.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set04\V004.vbb' ), 'N:\\Datasets\\Caltech\\set04\V004.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set04\V005.vbb' ), 'N:\\Datasets\\Caltech\\set04\V005.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set04\V006.vbb' ), 'N:\\Datasets\\Caltech\\set04\V006.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set04\V007.vbb' ), 'N:\\Datasets\\Caltech\\set04\V007.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set04\V008.vbb' ), 'N:\\Datasets\\Caltech\\set04\V008.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set04\V009.vbb' ), 'N:\\Datasets\\Caltech\\set04\V009.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set04\V010.vbb' ), 'N:\\Datasets\\Caltech\\set04\V010.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set04\V011.vbb' ), 'N:\\Datasets\\Caltech\\set04\V011.txt', 0 )


vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set05\V000.vbb' ), 'N:\\Datasets\\Caltech\\set05\V000.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set05\V001.vbb' ), 'N:\\Datasets\\Caltech\\set05\V001.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set05\V002.vbb' ), 'N:\\Datasets\\Caltech\\set05\V002.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set05\V003.vbb' ), 'N:\\Datasets\\Caltech\\set05\V003.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set05\V004.vbb' ), 'N:\\Datasets\\Caltech\\set05\V004.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set05\V005.vbb' ), 'N:\\Datasets\\Caltech\\set05\V005.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set05\V006.vbb' ), 'N:\\Datasets\\Caltech\\set05\V006.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set05\V007.vbb' ), 'N:\\Datasets\\Caltech\\set05\V007.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set05\V008.vbb' ), 'N:\\Datasets\\Caltech\\set05\V008.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set05\V009.vbb' ), 'N:\\Datasets\\Caltech\\set05\V009.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set05\V010.vbb' ), 'N:\\Datasets\\Caltech\\set05\V010.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set05\V011.vbb' ), 'N:\\Datasets\\Caltech\\set05\V011.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set05\V012.vbb' ), 'N:\\Datasets\\Caltech\\set05\V012.txt', 0 )


vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V000.vbb' ), 'N:\\Datasets\\Caltech\\set06\V000.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V001.vbb' ), 'N:\\Datasets\\Caltech\\set06\V001.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V002.vbb' ), 'N:\\Datasets\\Caltech\\set06\V002.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V003.vbb' ), 'N:\\Datasets\\Caltech\\set06\V003.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V004.vbb' ), 'N:\\Datasets\\Caltech\\set06\V004.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V005.vbb' ), 'N:\\Datasets\\Caltech\\set06\V005.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V006.vbb' ), 'N:\\Datasets\\Caltech\\set06\V006.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V007.vbb' ), 'N:\\Datasets\\Caltech\\set06\V007.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V008.vbb' ), 'N:\\Datasets\\Caltech\\set06\V008.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V009.vbb' ), 'N:\\Datasets\\Caltech\\set06\V009.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V010.vbb' ), 'N:\\Datasets\\Caltech\\set06\V010.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V011.vbb' ), 'N:\\Datasets\\Caltech\\set06\V011.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V012.vbb' ), 'N:\\Datasets\\Caltech\\set06\V012.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V013.vbb' ), 'N:\\Datasets\\Caltech\\set06\V013.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V014.vbb' ), 'N:\\Datasets\\Caltech\\set06\V014.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V015.vbb' ), 'N:\\Datasets\\Caltech\\set06\V015.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V016.vbb' ), 'N:\\Datasets\\Caltech\\set06\V016.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V017.vbb' ), 'N:\\Datasets\\Caltech\\set06\V017.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set06\V018.vbb' ), 'N:\\Datasets\\Caltech\\set06\V018.txt', 0 )


vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set07\V000.vbb' ), 'N:\\Datasets\\Caltech\\set07\V000.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set07\V001.vbb' ), 'N:\\Datasets\\Caltech\\set07\V001.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set07\V002.vbb' ), 'N:\\Datasets\\Caltech\\set07\V002.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set07\V003.vbb' ), 'N:\\Datasets\\Caltech\\set07\V003.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set07\V004.vbb' ), 'N:\\Datasets\\Caltech\\set07\V004.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set07\V005.vbb' ), 'N:\\Datasets\\Caltech\\set07\V005.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set07\V006.vbb' ), 'N:\\Datasets\\Caltech\\set07\V006.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set07\V007.vbb' ), 'N:\\Datasets\\Caltech\\set07\V007.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set07\V008.vbb' ), 'N:\\Datasets\\Caltech\\set07\V008.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set07\V009.vbb' ), 'N:\\Datasets\\Caltech\\set07\V009.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set07\V010.vbb' ), 'N:\\Datasets\\Caltech\\set07\V010.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set07\V011.vbb' ), 'N:\\Datasets\\Caltech\\set07\V011.txt', 0 )

vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set08\V000.vbb' ), 'N:\\Datasets\\Caltech\\set08\V000.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set08\V001.vbb' ), 'N:\\Datasets\\Caltech\\set08\V001.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set08\V002.vbb' ), 'N:\\Datasets\\Caltech\\set08\V002.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set08\V003.vbb' ), 'N:\\Datasets\\Caltech\\set08\V003.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set08\V004.vbb' ), 'N:\\Datasets\\Caltech\\set08\V004.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set08\V005.vbb' ), 'N:\\Datasets\\Caltech\\set08\V005.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set08\V006.vbb' ), 'N:\\Datasets\\Caltech\\set08\V006.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set08\V007.vbb' ), 'N:\\Datasets\\Caltech\\set08\V007.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set08\V008.vbb' ), 'N:\\Datasets\\Caltech\\set08\V008.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set08\V009.vbb' ), 'N:\\Datasets\\Caltech\\set08\V009.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set08\V010.vbb' ), 'N:\\Datasets\\Caltech\\set08\V010.txt', 0 )

vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set09\V000.vbb' ), 'N:\\Datasets\\Caltech\\set09\V000.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set09\V001.vbb' ), 'N:\\Datasets\\Caltech\\set09\V001.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set09\V002.vbb' ), 'N:\\Datasets\\Caltech\\set09\V002.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set09\V003.vbb' ), 'N:\\Datasets\\Caltech\\set09\V003.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set09\V004.vbb' ), 'N:\\Datasets\\Caltech\\set09\V004.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set09\V005.vbb' ), 'N:\\Datasets\\Caltech\\set09\V005.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set09\V006.vbb' ), 'N:\\Datasets\\Caltech\\set09\V006.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set09\V007.vbb' ), 'N:\\Datasets\\Caltech\\set09\V007.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set09\V008.vbb' ), 'N:\\Datasets\\Caltech\\set09\V008.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set09\V009.vbb' ), 'N:\\Datasets\\Caltech\\set09\V009.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set09\V010.vbb' ), 'N:\\Datasets\\Caltech\\set09\V010.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set09\V011.vbb' ), 'N:\\Datasets\\Caltech\\set09\V011.txt', 0 )


vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set10\V000.vbb' ), 'N:\\Datasets\\Caltech\\set10\V000.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set10\V001.vbb' ), 'N:\\Datasets\\Caltech\\set10\V001.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set10\V002.vbb' ), 'N:\\Datasets\\Caltech\\set10\V002.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set10\V003.vbb' ), 'N:\\Datasets\\Caltech\\set10\V003.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set10\V004.vbb' ), 'N:\\Datasets\\Caltech\\set10\V004.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set10\V005.vbb' ), 'N:\\Datasets\\Caltech\\set10\V005.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set10\V006.vbb' ), 'N:\\Datasets\\Caltech\\set10\V006.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set10\V007.vbb' ), 'N:\\Datasets\\Caltech\\set10\V007.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set10\V008.vbb' ), 'N:\\Datasets\\Caltech\\set10\V008.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set10\V009.vbb' ), 'N:\\Datasets\\Caltech\\set10\V009.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set10\V010.vbb' ), 'N:\\Datasets\\Caltech\\set10\V010.txt', 0 )
vbb('vbbSaveTxt', vbb('vbbLoad', 'N:\\Datasets\\Caltech\\annotations\\set10\V011.vbb' ), 'N:\\Datasets\\Caltech\\set10\V011.txt', 0 )

